/**
 * This module is responsible for the layout of our UI.
 * 
 * @Author Preston Knepper & Dalton Rogers
 * @Version 12/4/2024
 */

// import the needed libraries
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Header } from "./header";
import { RightSide } from "./right_side_component";
import { LeftSide } from "./left_side_pane";

// define the fonts used
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Generates the root layout of the program.
 * 
 * @returns html of the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="layout">
          <Header />
          <div style={{ marginTop: "80px", display: "flex", height: "calc(100vh - 80px)" }}>
            <LeftSide>{children}</LeftSide>
            <div style={{ width: "50%"}}>
              <RightSide />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
