[package]
name = "rust_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio-native-tls", "migrate"] }
dotenvy = "0.15"
futures = "0.3"